#!/usr/bin/env python
# -*- coding: utf-8 -*-

try:
    from setuptools import setup, find_packages
except ImportError:
    from distutils.core import setup

readme = open('README.md').read()

setup(
    name='rcportal_migration',
    version='0.1.0',
    description='crams nectar rcportal migration',
    long_description=readme,
    author='Simon Yu, Melvin Luong, mohamed feroze',
    author_email='xm.yuau@gmail.com, melvin.luong@monash.edu, mohamed.feroze@monash.edu',
    url='https://github.com/monash-merc/rcportal_migration',
    packages=find_packages(exclude=['tests', 'local']),
    include_package_data=True,
    install_requires=['Babel==1.3',
                      'Django==1.8.7',
                      'Pillow==2.8.1',
                      'Pygments==2.0.2',
                      'Werkzeug==0.10.4',
                      'amqp==1.4.6',
                      'anyjson==0.3.3',
                      'argparse==1.4.0',
                      'billiard==3.3.0.20',
                      'coverage==3.7.1',
                      'debtcollector==1.1.0',
                      'django-babel==0.4.0',
                      'django-common-helpers==0.7.0',
                      'django-cors-headers==1.1.0',
                      'django-extensions==1.5.5',
                      'django-filter==0.10.0',
                      'django-jenkins==0.18.1',
                      'django-nose==1.4.1',
                      'djangorestframework==3.2.2',
                      'djangular==0.2.7',
                      'gunicorn==19.3.0',
                      'httpie==0.9.2',
                      'iso8601==0.1.11',
                      'kombu==3.0.26',
                      'monotonic==0.5',
                      'msgpack-python==0.4.6',
                      'mysqlclient==1.3.7',
                      'netaddr==0.7.18',
                      'netifaces==0.10.4',
                      'nose==1.3.6',
                      'numpy==1.9.2',
                      'oslo.config==3.2.0',
                      'oslo.i18n==3.1.0',
                      'oslo.serialization==2.2.0',
                      'oslo.utils==3.3.0',
                      'pbr==1.8.1',
                      'prettytable==0.7.2',
                      'pyparsing==2.0.3',
                      'python-dateutil==2.4.2',
                      'pytz==2015.4',
                      'requests==2.9.1',
                      'rest-condition==1.0.2',
                      'six==1.9.0',
                      'sqlparse==0.1.16',
                      'stevedore==1.10.0',
                      'wrapt==1.10.6',
                      'simplejson==3.8.2',
                      ],
    license="GPLv3+",
    zip_safe=False,
    keywords='monash-merc/rcportal_migration',
    platforms='Ubuntu16',
    classifiers=[
        'Development Status :: 2 - Pre-Alpha',
        'Intended Audience :: Developers',
        'License :: OSI Approved :: GNU General Public License v3 or '
        'later (GPLv3+)',
        'Natural Language :: English',
        'Programming Language :: Python :: 3.5',
    ],
)
